apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  nineantrakidsfrontv2
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://192.168.89.129:6443

  source:
    path: 9antraKidsFrontV2 # you chould provide the folder in the git repo
    repoURL: "https://github.com/FtouhiS/argocd.git" # the url of the github repository
    targetRevision: HEAD # the branch of the github repository.We can use Head or a specific version
  syncPolicy:
    automated: {} # This will detect changes automatically from the repository
    syncOptions:
      - CreateNamespace=true
