apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nineantrakidsfrontv2
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc

  source:
    path: 9antraKidsFrontV2 # specify the folder in the git repo
    repoURL: "https://github.com/FtouhiS/argocd.git" # URL of the GitHub repository
    targetRevision: HEAD # branch of the GitHub repository (HEAD or a specific version)
  syncPolicy:
    automated: # This will detect changes automatically from the repository
      prune: true # Optional: Automatically delete resources that are no longer tracked in Git
      selfHeal: true # Optional: Automatically correct drift from the desired state
    syncOptions:
      - CreateNamespace=true
